baseURL: https://timwmillard.github.io
languageCode: en-au
defaultContentLanguage: en
title: Tim Millard
theme: papercss-hugo-theme
googleAnalytics: UA-123456789-1
disqusShortname: timwmillard

privacy:
  disqus:
    disable: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  homeMetaContent: A blog by Tim Millard about stuff.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  navTitleLink: /

menu:
  nav:
    - name: Tech
      url: /tech
      weight: 10
    - name: Animation
      url: /animation
      weight: 20
    - name: About
      url: /about/
      weight: 40

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
